apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-sops-plugin
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cmp-cm
data:
  sops.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: sops
    spec:
      version: v1.0
      generate:
        command: ["sops"]
        args: ["-d", "--output-type", "yaml", "$ARGOCD_ENV_APP_SOURCE_PATH"]
