---
apiVersion: v1
kind: Secret
metadata:
  name: sops-age-key
  namespace: argocd
type: Opaque
stringData:
  keys.txt: |
    {{ lookup('ansible.builtin.file', role_path + '/files/age-key.txt') | indent(4) }}
