$ANSIBLE_VAULT;1.1;AES256
37363461646634303834326265346663653433623436666235636565663233383839366133353064
3166303464383038613032383031613333343561626531630a306338666465323264356462363934
63363438366537623133663137613837303632643135626461363134623632346232373638633465
3663393433323462360a343830396365346561353262373766323262306631316232313233306134
63666339343365616136336534336237396335353666353739643464363332346161366565376664
66366262653239393733323463353065633738306336333063396164343234373636663963373835
31616266376230663265346530353863383436313834636539663266333363333762386364643961
63616132383338303234663166376338373737393465626239383464323432326536646137643037
39353532356238393064323232363365666235666564356164373066396133333762393466313565
32356436653335313163393539336331623238333033643530633465333130386339616135326265
35643539386639653739633938373335616233316264663837333630323938376533653566316635
38333837303165663561303236333935396662363366336530653031616164336566623165636666
30356165336265613730363137653936353636663636643666353339366537376532623337666232
33613531346637373334373934316332316262366361333533643766616462303139326336333932
39333334303861366539376666333638306461323166643436393532306332393461666462303639
39653438303839363337313638636530346364656534333633313031653437383332313936383331
37373636613631666636356165396239383632373336336235663062346461653636353062356534
32353134393638356334373839633031336165303131656530633262323065356666303465383765
38303961383336376266666137396665336365363635333562356431396539343336326231386632
63613463343936653939
